version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - "6379:6379"
